declare namespace entry {
  function init(dataDir: string): void;
  function setBaseUrl(service: string, url: string): void;
  function secureGet(key: string): string;
  function secureSet(key: string, value: string): void;
  function prefGet(key: string): string;
  function prefSet(key: string, value: string): void;
  function prefSetBatch(jsonObject: string): void;
  function getReadingHistory(): string;
  function saveReadingHistory(json: string): boolean;
  function getBookmarks(): string;
  function saveBookmarks(json: string): boolean;
  function getDownloads(): string;
  function saveDownloads(json: string): boolean;
  function apiSignIn(username: string, password: string): string;
  function apiSignInAsync(username: string, password: string): Promise<string>;
  function apiSignOut(): string;
  function apiGetUserInfo(): string;
  function apiGetUserInfoAsync(): Promise<string>;
  function apiWarmConnectionAsync(): Promise<string>;
  function apiGetIndex(random: number, recent: number): string;
  function apiSearch(name: string, page: number, limit: number): string;
  function apiSearchAsync(name: string, page: number, limit: number): Promise<string>;
  function apiGetRecent(page: number, limit: number): string;
  function apiGetRecentAsync(page: number, limit: number): Promise<string>;
  function apiGetHot(page: number, limit: number): string;
  function apiGetHotAsync(page: number, limit: number): Promise<string>;
  function apiGetAllBooks(page: number, limit: number): string;
  function apiGetAllBooksAsync(page: number, limit: number): Promise<string>;
  function apiGetBookDetail(bookId: number): string;
  function apiGetBookDetailAsync(bookId: number): Promise<string>;
  function apiDeleteBook(bookId: number): string;
  function apiSetFavorite(bookId: number, favorite: boolean): string;
  function apiSetFavoriteAsync(bookId: number, favorite: boolean): Promise<string>;
  function apiGetBookNav(): string;
  function apiGetBookNavAsync(): Promise<string>;
  function apiGetReadingList(page: number, limit: number): string;
  function apiGetReadingListAsync(page: number, limit: number): Promise<string>;
  function apiGetFavorites(page: number, limit: number): string;
  function apiGetFavoritesAsync(page: number, limit: number): Promise<string>;
  function apiGetMessages(page: number, limit: number): string;
  function apiGetMessagesAsync(page: number, limit: number): Promise<string>;
  function apiGetMetaList(type: string, page: number, limit: number): string;
  function apiGetMetaListAsync(type: string, page: number, limit: number): Promise<string>;
  function apiGetMetaBooks(type: string, name: string, page: number, limit: number): string;
  function apiGetMetaBooksAsync(type: string, name: string, page: number, limit: number): Promise<string>;
  function apiGetAdminBooks(page: number, limit: number): string;
  function apiGetAdminBooksAsync(page: number, limit: number): Promise<string>;
  function apiGetAdminUsers(page: number, limit: number): string;
  function apiSoNovelSearch(keyword: string): string;
  function apiSoNovelFetchBook(paramsJson: string, destPath: string): string;
  function apiDownloadBook(bookId: number, format: string, destPath: string): string;
  function apiDownloadBookAsync(bookId: number, format: string, destPath: string): Promise<string>;
  function apiDownloadAudioFileAsync(bookId: number, filename: string, destPath: string): Promise<string>;
  function apiEditBook(bookId: number, payloadJson: string): string;
  function apiEditBookAsync(bookId: number, payloadJson: string): Promise<string>;
  function apiGetBookRefer(bookId: number): string;
  function apiGetAudioFiles(bookId: number): string;
  function apiMarkMessageRead(messageId: number): string;
  function apiMarkMessageReadAsync(messageId: number): Promise<string>;
  function fetchImageCache(url: string, destPath: string): string;
  function fetchImageCacheAsync(url: string, destPath: string): Promise<string>;
}

export default entry;
